[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
crowd_funding = "Eis8iYtZBk7HmgBEvgj1soAtCZjqV8mDcRbcqo1U4TPc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "solana/my_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
